### PR TITLE
[Issue 1500] CsvReader - allow mapping to dynamic properties

### PR DESCRIPTION
**Pull request by ruslanss**

### CODE REVIEW

**Comment by ruslanss** [comment]
Not sure why build failed? Says "The reference assemblies for .NETFramework,Version=v4.5 were not found". I hope this isn't something I've broken 🙄

**Comment by ruslanss** [comment]
Also, it needs DRY applied in ClassMap`1.cs but wasn't sure how to add a common private method without an "out member" parameter 🤷‍♂️ can you help, please?

**Comment by JoshClose** [comment]
I never got AppVeyor working correctly. I'll try and fix it some day again.

**Comment by ruslanss** [comment]
might be something i can help with? I've used AppVeyor before.  let me know

**Comment by michal-mad** [comment]
Is this going to be merged soon? I am really waiting for this change.

**Pull request merged**
