### PR TITLE
Fixes #2081

### LINKED ISSUE #2069: ValidateHeader - At runtime getting "This Operation is only valid on generic types.
**Describe the bug**
At runtime getting "This Operation is only valid on generic types.

**To Reproduce**
```
            using var ms = new MemoryStream(file.Data);
            using var reader = new StreamReader(ms);
            using var csv = new CsvReader(reader, config);

            csv.Context.TypeConverterOptionsCache.GetOptions<string>().NullValues.Add("NULL");
            csv.Context.TypeConverterOptionsCache.GetOptions<int?>().NullValues.Add("NULL");
            csv.Context.RegisterClassMap(csvClassMapType);

            csv.Read();
            csv.ReadHeader();
            **csv.ValidateHeader<ClientModelImportClassMap>();**

            result = csv.GetRecords<ClientModelImportCsv>().ToList();

public class ClientModelImportClassMap : ClassMap<ClientModelImportCsv>
{
    public ClientModelImportClassMap()
    {
        Map(m => m.PhysicalName).Name("COLUMN_NAME", "COLUMNNAME", "COLUMNPHYSICALNAME");
        Map(m => m.TableName).Name("TABLE_NAME", "TABLENAME", "TABLEPHYSICALNAME");
        Map(m => m.ColumnOrderInTable).Name("ORDINAL_POSITION", "ORDINALPOSITION", "COLUMNORDERINTABLE").Default(0);
        Map(m => m.IsNullable).Name("IS_NULLABLE", "ISNULLABLE").Default("YES");
        Map(m => m.ColumnDataType).Name("DATA_TYPE", "DATATYPE").Default(null);
        Map(m => m.Size).Name("CHARACTER_MAX_LENGTH", "CHARACTER_MAXIMUM_LENGTH", "CHARACTERMAXIMUMLENGTH", "CHARACTERMAXLENGTH", "SIZE");
        Map(m => m.Precision).Name("NUMERIC_PRECISION", "NUMERICPRECISION", "PRECISION");
        Map(m => m.Scale).Name("NUMERIC_SCALE", "NUMERICSCALE", "SCALE");
    }
}
```

**Expected behavior**
Code works in 27.2.1, doesn't work in 29.0.0 or 30.0.0. We thought it was b/c of this noted breaking change. 
Fixed constructor mapping issue where parameter has a type converter but would still try and use constructor mapping.

**Screenshots**
image

**Additional context**
We would like to use the more modern version of the code. Just hoping we could make a small adjustment to our code and it would work.

### LINKED ISSUE #2081: WriteRecordsAsync - at runtime getting "This Operation is only valid on generic types."
Writing objects into CSV throws "This Operation is only valid on generic types." runtime error.
Following code worked correctly until version 28.0.1, error occurs from 29.0.0 and even in 30.0.1.

```
IEnumerable<MyType> records = ...
await csv.WriteRecordsAsync<MyType>(records);
```

There is some problem with CsvHelper.CsvContext.AutoMap

I use only [Name("fieldname")] for properties of MyType, no custom classmaps.

image

### PR DESCRIPTION
**Pull request by MiblaCz**
Fixes #2081 Fixes #2069
Fixes "This Operation is only valid on generic types." error caused by calling type.GetGenericTypeDefinition on non generic types.

### CODE REVIEW

**Comment by dylanvdmerwe** [comment]
Blocked on this from version 29.x upwards. Any idea when this can be released?

**Comment by MiblaCz** [comment]
Fixes #2081

**Comment by enkodellc** [comment]
This is roadblocking me as well. Does anyone else have a repo that has most of the PR's in them. Seems like a simple PR to merge so is this repo still being maintained?

**Review by danalexandrunicoara — APPROVED** [review]

**Comment by ben-balre** [comment]
Hi - could this one be merged please? It's currently blocking us from being able to update to the latest version - many thanks.

**Pull request merged**
