### PR TITLE
stuff

### PR DESCRIPTION
**Pull request by SimonCropp**
* redundant usings 
 * inline outs
 * make indents consistent
 * spelling

### CODE REVIEW

**Comment by JoshClose** [comment]
Thank you for putting them into separate logical commits. 

Did you use a tool for spelling? 

I hadn't heard of EditorConfig before, but I apparently had a plugin installed for it. I'll be using that from now on.

**Comment by SimonCropp** [comment]
The newest version of resharper has spelling built in

**Comment by SimonCropp** [comment]
I will do another round in a new pr once u have chose what to use from this

**Comment by JoshClose** [comment]
It's all in there.

**Comment by JoshClose** [comment]
I just turned a bunch of that stuff on in visual studio settings. Do all the C# settings work in the .editorconfig file?

**Comment by SimonCropp** [comment]
> Do all the C# settings work in the .editorconfig file?

no. but many do eg

 *  https://github.com/Fody/Home/blob/master/src/RepoSync/Source/.editorconfig
 * https://github.com/dotnet/roslyn/blob/master/.editorconfig

**Pull request merged**
