### PR TITLE
3.0.0 (RC5 / HEAD): ConvertUsing fails by default when csv file has no field with property name

### PR DESCRIPTION
**Pull request by StefanBertels**
See my last comment #747.

I think the attached test should succeed without removing the commented line.

### CODE REVIEW

**Comment by StefanBertels** [comment]
Two notes:

Seems it's enough to call `Map(e => e.MyProperty).Name("").ConvertUsing(...)` to make it work. But this isn't obvious.

Maybe one option would be to implicitely reset property name by calling ConvertUsing. At least my shortcut extension `ConvertPropertyUsing` (comment 3 in #698) would fail, then. But I could add explicit `.Name("MyProperty")` then to re-enable it.

Maybe this is another reason to allow something like my ConvertPropertyUsing extensions internally, so one could use full custom mode (working on IReaderRow, names cleared) and simple "type conversion" mode just converting string to property type and vice versa (working on raw value, name field implicitely set as it is now).

**Comment by JoshClose** [comment]
Isn't this actually appropriate? Header validation is matching against the mapped headers. If you don't specify a name, it'll use the property name. If the validation doesn't find a mapping for a header, it'll throw.

In your case, the correct thing would be to do

```cs
Map( m => m.StringColumn ).Name( "string.3" ).ConvertUsing( row => row.GetField( "string.3" ) );
```

since it's the `string.3` column it's matched to.

Otherwise you can turn the validation off.

**Comment by StefanBertels** [comment]
There are multiple ways to workaround. But it took me some time to find out what's wrong and I'm already familiar with your fine library. What about other users? Should be easy (enough) for them...

But there are other issues: I use ConvertUsing to combine multiple fields. And someone might use column index. I personally solved it with `.Name("")` which seems quite clean to me.

**Comment by JoshClose** [comment]
I think turning validation off is the appropriate thing to do if you don't care about all the fields being mapped. Is the description in the exception good enough? Having validation on by default makes sense to me because in a normal case, you'd want to know if your file is missing some columns you're expecting. 

Do you want to have exceptions occur when a field is missing but you don't want `ConvertUsing`. I guess I can kind of see your point. If you're mapping the file and use `ConvertUsing`, you're not expecting that column to necessarily exist. 

Maybe I can not do it if `ConvertUsing` is specified and there is no `Name` or `Index` set. If there is a `Name` or `Index` specified, then they are expecting it. I guess that makes sense.  Constant would probably be another one that would need to be ignored. Does it make sense to only validate member maps that had a `Name` or `Index` set?

I'm going to leave this mess so you can see my though process here. lol

**Comment by JoshClose** [comment]
This is fixed. I'm checking if `ConvertUsing` or `Constant` were used and not failing validation if they are. This will be in 3.0.1.

**Pull request merged**
