### PR TITLE
Adding IsOptional mapping option

### LINKED ISSUE #339: Ignore WillThrowOnMissingField for certain fields?
Hello.  Is there a way to specify that a particular field might be missing, and if it is, then don't throw even if WillThrowOnMissingField = true?  For example, suppose you have a csv file that must have one set of fields, but another set of fields are optional.  Couldn't figure out how to configure for this scenario.  I could use a map with ConvertUsing where I TryGetField and if the field doesn't exist, set the property to some default value or null.  But with the out var, that lambda is looking pretty ugly =).  Any better way?

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #339

### CODE REVIEW

**Comment by StefanBertels** [comment]
I like this simple solution. It does not allow setting a fallback value but is easy and useful for most cases.

For the record: I use this custom extension function for full flexibility:

```
    public static MemberMap<TClass, T> ConvertOptionalFieldUsing<TClass, T>(this MemberMap<TClass, T> map,
        Func<string, T> readExpression,
        Func<IReaderRow, T> fallbackExpression = null,
        Func<T, string> writeExpression = null) =>
        map.ConvertUsing(row =>
                row.TryGetField(map.Data.Names.First(), 0, out string result)
                    ? readExpression(result)
                    : (fallbackExpression ?? (_ => default(T))).Invoke(row))
            .ConvertUsing(obj =>
                (writeExpression ?? throw new Exception($"no {nameof(writeExpression)} given for {map.Data?.Names?.First()}"))
                .Invoke((T) (map.Data.Member as PropertyInfo).GetValue(obj))
            );
```

Can be used like this: 
```
   Map(e => e.IntColumn).ConvertOptionalFieldUsing(int.Parse); // read-only, fallback = default (i.e. 0)
   Map(e => e.IntColumn).ConvertOptionalFieldUsing(int.Parse, row => 17); // read-only, fallback another value (could be a different function, e.g. reading other fields by accessing 'row')
   Map(e => e.IntColumn).ConvertOptionalFieldUsing(int.Parse, row => 17, i => $"{i}");  // read + write + custom fallback value
   Map(e => e.IntColumn).Name("AnotherColumn").ConvertOptionalFieldUsing(readExpresssion: int.Parse, writeExpression: i => $"{i}");  // read + write + default fallback value (i.e. 0 for int), different column name.
```

While my extension allows many use cases (like type-safe parsing / formatting and custom fallback values) it uses low level info of CsvHelper class map data. I would be happy if we could have a KISS and integrated/supported solution like @sebastienros' `Optional` flag.

**Comment by JoshClose** [comment]
Would this resolve issue #1017 also?

**Comment by StefanBertels** [comment]
@amikulich and @zolrath might answer for themselves (#1017). But IMHO yes, that's exactly what this PR solves.

**Comment by gmackiewicz** [comment]
What is the status of this PR and when can be expected to be in production?
We could really use this solution, so we wouldn't have to insert any unnecessary hacks in code.

**Comment by amikulich** [comment]
I forked this repo in May and fixed the issue by: https://github.com/amikulich/CsvHelper/commit/3d3815c03b80de266081a30b276d4d93ae107b9a 

I can create a pull request to merge this to the original repository if necessary

**Comment by JoshClose** [comment]
In version 8.1.0 on nuget.

**Comment by SABARISHV06** [comment]
@JoshClose / @amikulich I am developing with the help of the testcases added by you guys. I don't find ValidateHeader() test cases after adding IsOptional field. Because I'm facing StackoverFlow exception, after validateHeader method. Can you guys help on this?

**Pull request merged**
