### PR TITLE
set default value  when delimiter is null.

### PR DESCRIPTION
**Pull request by netcore-jroger**
use cultureInfo.TextInfo.ListSeparator  when delimiter is null.

### CODE REVIEW

**Comment by netcore-jroger** [comment]
when use `new CsvConfiguration(CultureInfo.InvariantCulture, hasHeaderRecord: false)` will throw Object null reference exception.

**Comment by JoshClose** [comment]
Thanks. I took at different approach. I made them all nullable and set to null. If null, it will use the property as a default. This way I only have to specify defaults in one place. Except for `Delimiter` ironically, since that needs the culture to be set.

https://github.com/JoshClose/CsvHelper/blob/765fd7a4afe5b7dd329afeae168cf02aec9656d6/src/CsvHelper/Configuration/CsvConfiguration.cs#L289

**Comment by netcore-jroger** [comment]
I just found out that your master branch is what I want.
https://github.com/JoshClose/CsvHelper/blob/master/src/CsvHelper/Configuration/CsvConfiguration.cs#L337

Why not accept my PR first? Forget it.

**Comment by JoshClose** [comment]
> Why not accept my PR first? Forget it.

> ...I took at different approach. I made them all nullable and set to null. If null, it will use the property as a default. This way I only have to specify defaults in one place. Except for Delimiter ironically, since that needs the culture to be set.

**Pull request closed without merging**
