### PR TITLE
Fixes #2064

### LINKED ISSUE #2064: Documentation of several methods incorrect
I am currently documenting my project using SandCastle Help File Builder and created a referernce project for CsvHelper to be able to document my derived classes in my own project.

I found that there are several methods that have an "<inheritDoc/>" documentation, while these methods do not override/inherit from a base class. This gives warnings while trying to document my own classes (and missing documentation in the end). I have at least found the following methods that have incorrect inherited documentation:

- CsvHelper.CsvParser.ProcessRFC4180Field(System.Int32,System.Int32,System.Int32)
- CsvHelper.CsvParser.ProcessRFC4180BadField(System.Int32,System.Int32)
- CsvHelper.CsvParser.ProcessEscapeField(System.Int32,System.Int32)
- CsvHelper.CsvParser.ProcessNoEscapeField(System.Int32,System.Int32)
- CsvHelper.CsvParser.Dispose(System.Boolean)
- CsvHelper.CsvReader.ValidateHeader``1
- CsvHelper.CsvReader.ValidateHeader(System.Type)
- CsvHelper.CsvReader.ValidateHeader(CsvHelper.Configuration.ClassMap,System.Collections.Generic.List{{CsvHelper.InvalidHeader}})
- CsvHelper.CsvReader.GetFieldIndex(System.String,System.Int32,System.Boolean)
- CsvHelper.CsvReader.GetFieldIndex(System.Collections.Generic.IEnumerable{{System.String}},System.Int32,System.Boolean,System.Boolean)
- CsvHelper.CsvReader.CanRead(CsvHelper.Configuration.MemberMap)
- CsvHelper.CsvReader.CanRead(CsvHelper.Configuration.MemberReferenceMap)
- CsvHelper.CsvReader.Dispose(System.Boolean)
- CsvHelper.CsvReader.CheckHasBeenRead
- CsvHelper.CsvReader.ParseNamedIndexes
- CsvHelper.CsvWriter.WriteDynamicHeader(System.Dynamic.IDynamicMetaObjectProvider)
- CsvHelper.CsvWriter.FlushBuffer
- CsvHelper.CsvWriter.FlushBufferAsync
- CsvHelper.CsvWriter.CanWrite(CsvHelper.Configuration.MemberMap)
- CsvHelper.CsvWriter.GetTypeForRecord``1(``0)
- CsvHelper.CsvWriter.SanitizeForInjection(System.String)
- CsvHelper.CsvWriter.WriteToBuffer(System.String)
- CsvHelper.CsvWriter.Dispose(System.Boolean)

### PR DESCRIPTION
**Pull request by MarcelVersteeg**
Pull request for issue #2064

### CODE REVIEW

**Comment by jzabroski** [comment]
When you create a PR, just type "Fixes #2064"

This is awesome BTW. Documentation needs improvement

**Comment by MarcelVersteeg** [comment]
> When you create a PR, just type "Fixes #2064"

Do I need to create a new PR?

**Comment by jzabroski** [comment]
You dont need to.  The issues are linked now.  I am guessing the ) caused the problem, but who knows.

**Comment by MarcelVersteeg** [comment]
@JoshClose: Any idea when a release containing this pull request may be available?

**Pull request merged**
