### PR TITLE
Fixes issues caused when \r appears at the end of the FieldReader buffer

### PR DESCRIPTION
**Pull request by jamesbascle**
Also adds a fix for #677 since it was a 1 line removal and I also ran into it, and it is wrong according to point 2.6 of the CSV RFC @ https://tools.ietf.org/html/rfc4180#section-2

Added a failing test.

### CODE REVIEW

**Comment by JoshClose** [comment]
There are 6 broken unit tests here. Having the failing test is the most important part though. I'll take a look at it today.

**Comment by jamesbascle** [comment]
Oh!  Sorry I'll look at those then.  I may have goofed on R# test runner hitting them all.

**Comment by JoshClose** [comment]
No worries. Since that unit test is there, I can fix it.

**Comment by jamesbascle** [comment]
Okay. My apologies...clearly it is a more complicated bug to fix than my hack thrown in there, heh.

**Comment by JoshClose** [comment]
This issue stems around the buffer running out and the current data being set on the field and raw record. Ideally, none of that happens. I'm going to look into taking the unread parts at the end of the buffer and putting it at the beginning of the buffer and just resetting the numbers. That way we shouldn't have to worry about these special cases.

**Comment by JoshClose** [comment]
I'm going to publish this fix first for you then make changes so hopefully we don't have to do this. Passing the boolean into `GetChar` seems hacky.

**Comment by jamesbascle** [comment]
Ahh. That is a cleverer way of handling the situation.  Thanks for the merge. Hopefully my attempt at a fix was helpful in illuminating the issue.

**Comment by JoshClose** [comment]
I merged that other one you referenced too, so both this are in there. There is a chi03 release on nuget now.

**Comment by JoshClose** [comment]
Check this out. Much more simple and should be less error prone. https://github.com/JoshClose/CsvHelper/commit/385af8056a901dbdbc5899cbac4af4030e65ab8d

**Comment by jamesbascle** [comment]
Thanks for the release!

I think the commit is nice.  It allows the buffer to grow to as big as it needs to be to accommodate the largest field.

The only thing I can criticize is that the buffer size configuration is now a bit misleading, since someone working in a memory constrained environment now has an unbounded memory allocation that they have no control over other than restricting field size in their application.

This is fine for me, as it's not a concern I have, but it is something to consider.

**Comment by JoshClose** [comment]
I thought about it just taking up the first portion of the buffer, but you may run into the issue where a field take up more than the buffer size. Then you'd run into the problem of pulling that data prematurely like it was happening before. The data will either be in the buffer, on in a field string, so that space is going to be taken up no matter what. The buffer won't continually grow either. It'll always be `Configuration.BufferSize` + whatever was left over; not just appending on to a growing buffer.

The buffer size is more about how much it'll pull from a stream at once.

**Comment by jamesbascle** [comment]
Oh I see.  I was thinking the whole field was going into the beginning of the new buffer, but it's just the few chars that aren't yet making their way into the field string builder, yes?

**Comment by JoshClose** [comment]
It would be the whole field because nothing it taken out of the buffer until the whole field is read. What was happening before is it was taking the partial field out and storing that, then reading the buffer, then would put the rest of the field in later. This is where there were so many special case issues. Now it's not taking anything out, but pre-pending it to the buffer instead. This will the whole field can still be taken out later from the buffer. The same memory is used either way. The old way was partially in a string, partially in a char[] (even though a string is just a char[] anyways). The new way is just keeping it all in a char[].

**Comment by jamesbascle** [comment]
Hm.  Then it seems like the buffer will grow to the size of the largest field then, no?

**Comment by JoshClose** [comment]
Only if that field crosses the buffer boundary and needs to read from the stream again, and only that once. Every time it does it, it creates a new buffer. 

If `Configuration.BufferSize = 2048` and the field spill over is `100`, the buffer will be `buffer = new char[2048 + 100]`. The next time there is a spill over of only 1, the buffer will be `buffer = new char[2048 + 1].

Whichever field is in the middle of being read will be the one that is put on the front of the new buffer, but only the portion that's already been read. Worst case scenario is the `largest field size - 1` because at least 1 char would have to go across the buffer.

The old way would have all those chars in a field string, so I believe this should be the same amount of memory as before.

Maybe I'm missing something?...

**Comment by jamesbascle** [comment]
Oh okay. I missed the reset of the length to the original size after the long field on line 98.  Cool.

**Pull request merged**
