### PR TITLE
Add project and tests to target .NET Core

### LINKED ISSUE #469: CoreCLR Support
Hey, 

At the outset, I'd like to thank you for taking time out to write this really nifty and clean library. Its my go to lib of choice for CSV handling on C#. 

Just wanted to know if you have anything on the roadmap for porting CsvHelper to CoreCLR? 

Cheers :beers:

### PR DESCRIPTION
**Pull request by twsouthwick**
This adds a new PCL that targets the .NET Core assemblies. This will work for .NET 4.6, ASP.NET 5, and Universal Windows Apps. It includes the same files as the .NET 4.0 version, just compiled to target 'dotnet' instead of '.NETFramework'.

This change also includes updates to the nuspec file so that NuGet can correctly determine where to put files, notably all the dependencies for libraries targeting dotnet must be explicitly listed. This is done automatically during the build process. The 4.0-client library is also being included in the NET 4.5 directory so it can be used correctly by the project.json system.

Fixes #469 and #463

### CODE REVIEW

**Comment by twsouthwick** [comment]
FYI This is similar to #445, but does not attempt to use the xproj system but rather a portable library with a csproj. This has very little code change, and just uses the same files with a few appropriate if/defs. This change will require VS 2015 w/ Windows 10 SDK 1.2 (for the new portable library system).

**Comment by JoshClose** [comment]
I think I'm going to go the `xproj` route. The `project.json` file allows me to have a single project and build to a bunch of different frameworks. It also has NuGet support built in.

I'll be publishing CoreCLR support within the next day here.

**Comment by twsouthwick** [comment]
Sounds good! Glad to see Core support :)

**Comment by JoshClose** [comment]
It's released now. :)

**Pull request closed without merging**
