### PR TITLE
Reduces Serializer/Parser interface members to only those items that are required by the Reader/Writer

### PR DESCRIPTION
**Pull request by christophano**
Work in progress, opened for feedback - related to #596.

I have created a base interface for `ICsvParser` named `IParser` which contains only the members required by `CsvReader`. I have also introduced a type argument to `CsvReader` defining the type of `IParser` to be used. A default `CsvReader` class has been introduced which defined `TParser` to be an `ICsvParser`. It has the specialised constructors - the base class only has the core constructor.

I've also done the same for `ICsvSerializer` and `CsvWriter`.

The end result for users of the library should be fairly transparent. They can still use the `CsvReader`/`CsvWriter` classes with all of the same constructors, methods and properties.

I'm considering going a step further and segregating some of the configuration interfaces. This may be slightly more complicated as there tends to be a single class which implements several configuration interfaces.

Any thoughts or feedback?

### CODE REVIEW

**Comment by jamesbascle** [comment]
I, for one, think this is a pretty great idea - especially considering the
decision by Josh to remove Excel support, as it will make it much easier
for those folks to implement their additions.  I'll get around to checking
out the code sometime this weekend to look at the implementation,

**Comment by jamesbascle** [comment]
Oh, you own the Excel project! Haha. Awesome.

**Comment by christophano** [comment]
Haha, yes the Excel project is mine, so these changes are outrageously selfish!
It would be useful for anyone else who wishes to implement their own adapters too though.

**Comment by christophano** [comment]
I've done a little bit of work to the configuration interfaces.
This does mean that the base `CsvReader<,>` and `CsvWriter<,>` classes (which are now abstract) now require 2 type arguments, but this shouldn't affect the end user, as they will still use the concrete `CsvReader` and `CsvWriter` classes, which should have the same surface as previously.

**Comment by JoshClose** [comment]
Lots of other changes happened that cause this not to be merged, and we discussed on the issue for this. If things need to be changed up, let me know soon, as I'll be releasing 3.0 soon now. Only a few issues left.

**Pull request closed without merging**
