### PR TITLE
IAsyncEnumerable support in CsvWriter

### LINKED ISSUE #1515: Add support for IAsyncEnumerable in CsvWriter
We are going to generate very big CSV files based on database queries. Our ORM (Entity Framework) returns IQueryable, and query is sent to database only when enumeration is starting.

Current implementation of CsvWriter.WriteRecordsAsync<T>() has foreach, and it internally calls IEnumerable.GetEnumerator(), and IEnumerator.MoveNext(). These methods are synchronous, so they block threads. For example, ORM sends query to database on first call to MoveNext(), and this method returns only when query is executed and results are returned to the client.

In order to make MoveNext() work in "async/await" style, our ORM allows to cast IQueryable (that actually type that implements many interfaces) to IAsyncEnumerable<T> and enumerate it by using "await foreach" (which calls MoveNextAsync() and other methods that don't block threads). 

I propose to add new method `WriteRecordsAsync<T>(IAsyncEnumerable<T> records)` that uses "await foreach" internally. Probably, with optional cancellationToken parameter.

Currently we need to write manual loop in order to generate CSV:
```
csvWriter.WriteHeader<OurEntity>();
await csvWriter.NextRecordAsync().ConfigureAwait(false);

await foreach (var record in query.AsAsyncEnumerable().WithCancellation(token).ConfigureAwait(false))
{
   csvWriter.WriteRecord(record);
   await csvWriter.NextRecordAsync().ConfigureAwait(false);
}
```

It seems to me that it's pretty common case, when CSV is generated from data, loaded by long I/O operations. And since IAsyncEnumerable is added to .NET Standard, it makes sense to implement aforementioned method.

### PR DESCRIPTION
**Pull request by Domanser**
Added method `WriteRecordsAsync<T>(IAsyncEnumerable<T> records, CancellationToken cancellationToken = default)` to CsvWriter class. Unlike existing `WriteRecordsAsync<T>(IEnumerable<T> records)`, this new method uses "await foreach" for non-blocking enumeration.
Covered with tests.

Also, some refactoring is made in CsvWriter (common functionality moved to private methods). If it's undesirable, I can revert this refactoring.

closes #1515

### CODE REVIEW

**Comment by b0** [comment]
Hi @JoshClose, @Domanser 

can this PR be reviewed? Would love to see this in some some of next versions and try it out... 
If help is needed - please write.

Best regards

**Comment by cuongle** [comment]
Hi @JoshClose 

Has feature has been release?

Thanks

**Comment by AlainH** [comment]
I would also love to see this implemented.

**Comment by JoshClose** [comment]
This was done at some point.

**Pull request closed without merging**
