### PR TITLE
Updates to enable custom mappings using attributes.

### PR DESCRIPTION
**Pull request by TonyValenti**
Hi @JoshClose ,
I did a minor refactoring to enhance the configuration process using attributes.

With this enhancement:
1.  Two new interfaces are introduced (````IMemberMapper```` and ````IMemberReferenceMapper````).
2.  The mapping attributes were tagged with the appropriate interfaces.
3.  The mapping logic was moved out of ````ClassMap```` into the corresponding class.
4.  ````ClassMap```` was refactored to call the interface method instead of having a hard-coded set of mappings.

This will allow developers to extend/customize the process by simply creating their own custom ````Attribute```` that implements ````IMemberMapper```` or ````IMemberReferenceMapper````.

Would you please let me know what we need to do to get this change committed?

Thanks so much!

### CODE REVIEW

**Comment by JoshClose** [comment]
I really like this. It's a breaking change though, so it will try and lump it in with some other breaking changes.

**Comment by TonyValenti** [comment]
Hey @JoshClose - Any thoughts on this?

**Comment by JoshClose** [comment]
> I really like this. It's a breaking change though, so it will try and lump it in with some other breaking changes.

**Comment by TonyValenti** [comment]
@JoshClose - Thanks!  I saw you had released a version bump and I was surprised that this didn't go in with that change.  Any thoughts on an ETA?

**Comment by JoshClose** [comment]
I want to include a few more breaking changes in with it when I do. I have some in mind. I just need to find some time to do them. ;)

**Comment by TonyValenti** [comment]
@JoshClose Any ETA on merge?

**Comment by JoshClose** [comment]
Thanks for the reminder. I'm working on a major breaking change at the moment and I'll lump this in with that.

**Comment by JoshClose** [comment]
This will be in 13.0.0 on NuGet soon.

**Pull request merged**
