### PR TITLE
A new PCL project that targets .NET 2.0

### PR DESCRIPTION
**Pull request by mattleibow**
This is mostly for iOS as it does not support `Expression` and the `Compile()` method.
iOS is not JIT, but rather AOT.

The new project is just a PCL version of the .NET 2.0 project. I am just using the 2.0 profile as this excludes the Expressions.

This is the same code changes as my other PR: #334, but without the component bits.
As that one was a big change, I can submit the actual component on your behalf. a.k.a. Xamarin will submit it. The publisher will be Xamarin Inc, but all credit and links will point to you. 

Let me know if this is a better option as we would really like to see your component in the Xamarin Component store.

### CODE REVIEW

**Comment by JoshClose** [comment]
Man, I need to take the time to do this soon.

**Comment by mattleibow** [comment]
No problem. I am sure you are not working on this library as your only project :)
You can also ask me to do things for you, as part of my job is to find great bits in the wild and make it available for Xamarin devs.

**Comment by JoshClose** [comment]
Are you still around @mattleibow ? I'm going through everything in the backlog until it's clear.

**Comment by JoshClose** [comment]
The library is netstandard2.0 now which I believe will work with Xamarin, though I haven't tried. All the other projects are removed. If there is something specific I need to do, let me know.

**Pull request closed without merging**
