### PR TITLE
Allow FieldHeaders to be set externally

### PR DESCRIPTION
**Pull request by mguinness**
Having the ability to set FieldHeaders property manually (when HasHeaderRecord is false) would be good.    This would be needed when headers aren't provided in the file and header names are needed during reading.

### CODE REVIEW

**Comment by jamesbascle** [comment]
Why not just use an index call on your mapping?

**Comment by mguinness** [comment]
Certain fields will be skipped therefore the ordinal position cannot be relied upon.

**Comment by jamesbascle** [comment]
But you said it has no headers either...

How can you know what is what?

**Comment by mguinness** [comment]
These field mappings are stored in a database.

**Comment by jamesbascle** [comment]
So, the field order changes, and there are no headers, and based on some logic you retrieve different field headers from the database, then you use these field headers in your Class Map?

**Comment by jamesbascle** [comment]
Also, the very fact of setting the field header property implies that the order is known in some capacity.

**Comment by mguinness** [comment]
No class map used, reading individual fields.  The fields and positions are defined on a per customer basis and some fields can be omitted.

**Comment by jamesbascle** [comment]
Yah, I guess that's what I'm getting at, is why aren't you using a class map with some configurable values?

Ultimately it's a fairly inconsequential change, but it ambiguates the API and makes the parser ever so slightly slower..

**Comment by jamesbascle** [comment]
Or even, just use the raw parser, if you know the field position you're looking for.

I just don't really get how this solves a problem that is not already solvable.  That's what i'm trying to understand.

**Comment by mguinness** [comment]
I understand that this is an edge case, but I can't see how this impairs the normal use of the library.  Unless you set the header in this fashion then nothing changes.  How is this different than reading the header from the file (in terms of performance)?  Personally I'd rather work with field names than ordinal positions.

**Comment by jamesbascle** [comment]
Is this just so you can use the indexer on each row with the strings?

**Comment by mguinness** [comment]
Yes, I see what you're getting at.  I could probably use a hash table to give me the index based on name.  I'll try this with the app I've inherited and see if it works.

**Comment by jamesbascle** [comment]
Cool.  Ultimately it's up to Josh whether to merge or not, I'm just trying to understand the real impetus.

**Comment by JoshClose** [comment]
What James said.

That's only there for holding the values found from the header of the file. If there is no header, you're doing things by index. To be able to manually set the header, you'll need to know the indices anyways. I think it's bad form for how the API and library work to set it and it will confuse people.

If you want to manually build up a mapping file on the fly, you're able to do that already.

**Pull request closed without merging**
