### PR TITLE
Allow to ovveride column naming when no headers are supplied

### PR DESCRIPTION
**Pull request by v12**
This PR adds new reader configuration option `DynamicHeaderValue` that allows to change how dynamic column names are generated.

`DynamicHeaderValue` function accepts a single argument, which is set to current column index.

Right now, column naming hardcoded to `Field{columnIndex + 1}`, whereas, in some cases, you may require this to be overriden and setting your own  function allows to use custom naming convention.

### CODE REVIEW

**Comment by v12** [comment]
Any chance that this PR ends up in master? 😃

**Comment by JoshClose** [comment]
Probably... I haven't had a chance to take a good look at it yet. ;)

**Comment by v12** [comment]
Ah, I see :) Thanks for the update Josh!

**Comment by v12** [comment]
Hey, is there anything I can help with to get this into the next release of CsvHelper?

It's been a while since this PR was opened 🙊

**Comment by JoshClose** [comment]
Sorry about that. I've been busy with work and also lost my house to a fire 2 months ago, so I've been dealing with the fallout of that. I will try and get to this soon.

**Comment by v12** [comment]
@JoshClose I'm really sorry to hear that. I wouldn't bother you if I knew that, my apologies. Hope everyone is ok!

**Comment by JoshClose** [comment]
Yes, everyone is fine. No one was home at the time. No worries. You had no way of knowing. I didn't announce it. ;) I'm trying to get to items when I find time, but ones that I know will take more time I've been putting on the back burner.

**Comment by v12** [comment]
Hi, any chance this can be reviewed?

**Comment by JoshClose** [comment]
Sorry, this was implemented in 26.0.0.

**Pull request closed without merging**
