### PR TITLE
Implementation of Contract Resovler to support DI frameworks

### PR DESCRIPTION
**Pull request by ravensorb**
The attached code implements a "contact resolver" concept that allows CsvHelper to read data into entities that are based on interfaces (or contain interfaces) as long as those interfaces are registered with some sort of DI framework that can effectively resolve them.

Note: If this comes across with multiple commits -- my apologizes as I did try to squash the commits (still learning git)

### CODE REVIEW

**Comment by jamesbascle** [comment]
The point of this is to enable reference maps to handle using a CsvClassMap<IT1> for an interface but be used by a class, T1, implementing that interface actually being present, correct?

**Comment by ravensorb** [comment]
yes or CsvClassMap that is using a concrete class that has a member that is an Interface

    public class Sample1
    {
         public IAddress Address {get; set;}
         public string Name {get; set;}
    }

    public interface ISample2
    {
         public Address Address {get; set; }
         public string Name {get; set;}
    }

    public interface ISample3
    {
         public IAddress Address {get; set; }
         public string Name {get; set;}
    }

would all work in a CsvClassMap

**Comment by jamesbascle** [comment]
Ahh okay, it just dawned on me that this is for reading and being able to create the interface implementations.  Makes sense.

Only thing I have to say, as someone with absolutely no authority over the code itself (other than as a user who has had to debug it many times), is that it's hard to tell exactly what is going on in the changes here because you have so many reformatting and settings changing commits.

**Comment by ravensorb** [comment]
I know :-/  I tried hard not to let those creep into the commits alas I was not too successful.  Some of the files were tab aligned, some where not, and some where mixed.  I am a tab aligned guy and my env is setup that way so it may have caused issues (sorry about that).

The basics are pretty simple.  I added a new Interface called IContractResolver and added a property to the CsvConfiguration and CsvClassMap to hold an "instance" of this resolver.  I created a default version of the ContractResolver and then I updated CsvReader and the ReflectionHelpers calls to use this ContractResolver to create a new instance - if the process failed or the Resolver doesn't know about the object type, the code just falls back to the previously existing logic.

Does that help?

**Comment by ravensorb** [comment]
Any chance of getting this included?  I have been using it in production for a while now and there have been no issues at all.

**Comment by JoshClose** [comment]
I haven't had a chance to take a good look at it. I looked over it quickly, and it seems like it's fine. I won't have a chance to merge the code in any time soon though. Hopefully I'll find some free time over Christmas break to do it. I don't get any days off, but things are usually a little more calm around that time.

**Comment by ravensorb** [comment]
Any thought on including this in the main fork? its been almost a year :)

**Comment by JoshClose** [comment]
I'll be getting to all the pull requests soon. I'm done with bugs, and almost done with features now, so it should be within a week or two. I'm working on this with pretty much all my free time to get this out. Stuff like this pull request have been sitting for too long.

**Comment by ravensorb** [comment]
Any chance you were able to take a look at this one?

**Comment by JoshClose** [comment]
No. It's too bad there isn't a blog sort of feature in github where I could post updates to. I've been taking a little break because of burnout. I worked on bugs and features for this project pretty much every night for about 2 months straight. I will be getting back to it soon though.

**Comment by ravensorb** [comment]
Ok, no worries - I'll see if I can redo my changes on the latest branch.  If I do -- think you could merge them pretty quickly?

**Comment by JoshClose** [comment]
I need to look over it again. I'm going to move some functionality out of
the core library and into separate contribute libraries. I'll need to set
where this belongs.

**Comment by john-mckillip** [comment]
Hi. Wondering if you were ever going to merge this functionality into Master? Not being able to work with interfaces and dependency injection is a pretty big disappointment with this otherwise great library you have.

**Comment by JoshClose** [comment]
This has been implemented. 8afd0cd6c33006f627f41da2ccb3fde4c7cabbe2 The source was too far away from this branch to merge and  I did things a little differently. You can use this functionality in the pre-release on nuget.

**Comment by john-mckillip** [comment]
Heck yeah man, thanks!

**Comment by JoshClose** [comment]
No problem. Let me know if you have any questions with the implementation. You should be able to just set `CsvHelper.ObjectResolver.Current`.

**Pull request closed without merging**
