### PR TITLE
Initial commit for .NET Core support

### LINKED ISSUE #415: Support for DNX Core?
Question, will there be any support for DNX Core in the future?

### PR DESCRIPTION
**Pull request by alexthissen**
Fix #415 .NET Core support (initial commit).
Still requires work on removing initial CsvHelper project and tests.

### CODE REVIEW

**Comment by JoshClose** [comment]
Did you follow Marc Gravell's guide? http://blog.marcgravell.com/2015/11/the-road-to-dnx-part-1.html

**Comment by alexthissen** [comment]
Hi Josh,


No, we didn't follow that guide. We (Lohith Niagara and myself) did the .NET Core support during the MVP Summit this year together with the ASP.NET team members. Andrew Nurse has been helping us out during the tricky part and the direction of the Core implementation and solution structure.

I didn't know the guide by Marc yet, but will have a look. Did you look at the contents of the pull request yet? What do you think?


Lohith and Alex






Sent from Surface





From: Josh Close
Sent: ‎Monday‎, ‎December‎ ‎21‎, ‎2015 ‎10‎:‎14‎ ‎PM
To: JoshClose/CsvHelper
Cc: Alex Thissen





Did you follow Marc Gravell's guide? http://blog.marcgravell.com/2015/11/the-road-to-dnx-part-1.html

**Comment by alexthissen** [comment]
Well, sorry to Lohith. His surname is actually Nagaraj, but autocorrect changed it to Niagara without me noticing. (Just happened again, twice)


Alex






Sent from Surface





From: Josh Close
Sent: ‎Monday‎, ‎December‎ ‎21‎, ‎2015 ‎10‎:‎14‎ ‎PM
To: JoshClose/CsvHelper
Cc: Alex Thissen





Did you follow Marc Gravell's guide? http://blog.marcgravell.com/2015/11/the-road-to-dnx-part-1.html

**Comment by beefo** [comment]
@JoshClose Any idea if/when we might see this branch merged in to get support for dnx?

**Comment by JoshClose** [comment]
Hopefully soon. It'll probably be the first thing I do.

**Comment by rposener** [comment]
+1 waiting for this merge

**Comment by JoshClose** [comment]
Did .NET Core RTM last week at build?

**Comment by rposener** [comment]
No RTW, but it has a go-live license (since RC1 last November), and with some longer-term projects we are starting them now (post-build) with new knowledge on the new framework.  https://github.com/aspnet/Home/wiki/Roadmap

**Comment by JoshClose** [comment]
I'll make this my priority.

**Comment by rposener** [comment]
Thanks - I know we are one of the early ones, but do appreciate it.  We enjoy the library - it's one of our go-to's for simple import/export functionality in our app.

**Comment by JoshClose** [comment]
I have it working with CoreCLR support. I just need to get it set up to work with the unit test projects and NCrunch. I made the main project (and now only project) the CoreCLR project. I created a CoreCLR compatibility layer for the older builds now, which ends up being a lot less pre-compiler directives, and no more inline directives (for the most part). I'll probably finish up the unit testing stuff tonight and publish by the end of the weekend here.

**Comment by JoshClose** [comment]
Version 2.14.0.0 has been published to NuGet and contains CoreCLR support. Let me know if you run into any issues.

I ended up not merging this because I needed to learn how it all works. I ended up doing things a little different than this pull request due to the previous mentioned issues.

Thanks for the pull request, and sorry it took so long to implement.

**Comment by JoshClose** [comment]
Btw, CoreCLR is really amazing. Having a single project is really nice.

**Comment by jamesbascle** [comment]
Great work Josh!  The solution structure was fairly intimidating before due to all the major versions and whatnot.  CsvHelper is a critical component of mine and many other's .NET toolkit, so seeing it ready for the future is great!

**Comment by JoshClose** [comment]
Hopefully it doesn't change much for the final release. ;)

**Comment by beefo** [comment]
Awesome! Thanks Josh!

**Comment by rposener** [comment]
Thank you, thank you!  Will be pulling it into my project today!

**Comment by alexthissen** [comment]
Great going, Josh. Hope that what we did was useful, inspirational, or motivational. It was certainly a great learning experience for Lohith and myself. 
Thanks on behalf of the community. :)

**Pull request closed without merging**
